version: "2"
services:
  web:
    container_name: "web"
    build:
      context: nginx/
    networks:
      magento:
        ipv4_address: 172.19.11.2
    ports:
      - 80:80
      - 443:443
    tty: true
    links:
      - fpm
      - db
    volumes_from:
      - appdata
    env_file:
      - ./global.env
    restart: always
    environment:
      - VIRTUAL_HOST=magento2.docker
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
  fpm:
    hostname: fpm.magento2.docker
    container_name: "fpm"
    networks:
      magento:
        ipv4_address: 172.19.11.3
    build:
      context: fpm/
    restart: always
    ports:
      - "9000:9000"
    links:
      - db
    volumes_from:
      - appdata
    env_file:
      - ./global.env
    tty: true 
  db:
    container_name: "db"
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    networks:
      magento:
        ipv4_address: 172.19.11.4
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
    ports:
      - "3306:3306"
    volumes_from:
      - dbdata
    tty: true
  cli:
    hostname: cli.magento2.docker
    container_name: "cli"
    networks:
      magento:
        ipv4_address: 172.19.11.5
    build:
      context: cli/
    links:
      - db
    volumes:
      - ~/.composer/cache:/root/.composer/cache
    privileged: true
    volumes_from:
      - appdata
    env_file:
      - ./global.env
      - ./composer.env
    environment:
      - M2SETUP_INSTALL_DB=true
      - M2SETUP_DB_HOST=db
      - M2SETUP_DB_NAME=magento2
      - M2SETUP_DB_USER=magento2
      - M2SETUP_DB_PASSWORD=magento2
      - M2SETUP_BASE_URL=http://magento2.docker/
      # - M2SETUP_SECURE_BASE_URL=https://magento2.docker/
      - M2SETUP_BACKEND_FRONTNAME=admin
      - M2SETUP_ADMIN_FIRSTNAME=Admin
      - M2SETUP_ADMIN_LASTNAME=User
      - M2SETUP_ADMIN_EMAIL=dennyliu2021@gmail.com
      - M2SETUP_ADMIN_USER=admin
      - M2SETUP_ADMIN_PASSWORD=password1
      - M2SETUP_VERSION=2.1.*
      # - M2SETUP_USE_SAMPLE_DATA=true
    stdin_open: true
    tty: true
  cron:
    build:
      context: cli/
    container_name: "cron"
    hostname: magento2-cron.docker
    networks:
      magento:
        ipv4_address: 172.19.11.6
    command: run-cron
    environment:
      - ENABLE_SENDMAIL=true
    volumes_from:
      - appdata
    links:
      - db

  appdata:
    image: tianon/true
    volumes:
      - ./../:/var/www/magento

  dbdata:
    image: tianon/true
    volumes:
      - /var/lib/mysql
networks:
  magento:
    name: magento
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
